# Prepare training data
TRAIN_DATA = [
    ("Create a new file", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Make a directory", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Delete a file", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Delete a folder", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Delete a directory", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Delete a account", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Open a directory", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Open a file", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Open a folder", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Open my directory", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Delete the system logs", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Copy the configuration file to backup", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("List all installed programs", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Check disk usage on drive C:", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Show network status", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Ping the local gateway", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Map network drive Z", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Disconnect mapped drive Z", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Restart the network service", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Open remote desktop connection", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Change the directory to C:\\Users\\", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Create a restore point", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Run system file checker", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Update group policy settings", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Display all running processes", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Clear the screen", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Set the system time", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Unlock a user account", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Mount a virtual disk", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Eject a mounted disk image", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Delete the system logs", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Copy the configuration file to backup", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("List all installed programs", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Check disk usage on drive C:", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Show network status", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Ping the local gateway", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Map network drive Z", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Disconnect mapped drive Z", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Restart the network service", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Open remote desktop connection", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Change the directory to C:\\Users\\", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Create a restore point", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Run system file checker", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Update group policy settings", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Display all running processes", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Clear the screen", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Set the system time", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Unlock a user account", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Mount a virtual disk", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Eject a mounted disk image", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Change file attributes to hidden", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Encrypt a file", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Decrypt a document", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Register a DLL file", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Unregister a DLL file", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Open Windows Firewall settings", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Configure a static IP address", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Release and renew IP address", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Perform a traceroute to google.com", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Update all drivers", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Create a virtual hard drive", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Format a secondary drive", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Partition a hard disk", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Assign a drive letter to a partition", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Remove a drive letter", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Extend a volume", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Shrink a volume", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Create a system repair disc", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Enter BIOS setup on startup", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Configure startup programs", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Set environment variables", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Enable system restore", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Disable system restore", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Enable remote desktop access", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Disable remote desktop access", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Add a user account", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Delete a user account", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Change the system performance settings", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("View system information", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Restore files from backup", {"cats": {"COMMAND": 1.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 0.0}}),

    ("Create an account on the website", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Generate a report using software", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the weather today?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Show me the latest news", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you make a cake?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Tell me about your features", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the theory of relativity", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you make a cake?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the capital of France?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Who is the CEO of Microsoft?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Tell me a joke", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Show me pictures of the Eiffel Tower", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain quantum mechanics", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What's the weather like in Tokyo?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Find recipes for vegetarian lasagna", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How many languages are spoken in India?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the top movies of 2020?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the life cycle of a butterfly", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the theory of evolution?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Who discovered penicillin?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Show me the latest fashion trends", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Play the song 'Bohemian Rhapsody'", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Read me the news about the Olympics", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Translate 'hello' into Spanish", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How to fix a flat tire?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Find the nearest pizza restaurant", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Give me directions to the nearest hospital", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Recommend good books on World War II", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Tell me about the life of Nelson Mandela", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Who won the Nobel Prize in Physics in 2020?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Show me reviews for the latest Marvel movie", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the nutritional facts of broccoli?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Is there any good sushi restaurant nearby?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("When is the next solar eclipse?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do I apply for a patent?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the symptoms of the flu?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the stock market trends of last month", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Provide a summary of 'To Kill a Mockingbird'", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the major cities in Japan?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Who wrote 'Pride and Prejudice'?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Calculate the circumference of the earth", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Show current trends in AI technology", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What causes rainbows?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Who invented the telephone?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Give directions to the Statue of Liberty", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What's the score of the latest NFL game?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Recommend a good science fiction book", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the principles of solar panels", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do I implement a linked list in Java?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the difference between an array and a list in Python?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the concept of recursion in computer programming", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you describe how to use loops in C++?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the best practices for error handling in JavaScript?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do I sort an array in descending order using Swift?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is a lambda function in Python?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Show examples of polymorphism in Object-Oriented Programming", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do I connect to a database using PHP?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the MVC architecture with examples", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the use of decorators in Python?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How to handle state management in React?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you explain the use of the 'this' keyword in JavaScript?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are closures in JavaScript and how are they used?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do I perform a merge sort in a C# program?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain asynchronous programming in Node.js", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are generics in Java and why use them?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the process of normalization in database design", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How can I use recursion to solve the Tower of Hanoi problem?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is functional programming and how does it differ from OOP?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
     ("How do I create a REST API in Flask?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are web sockets and how do I implement them in JavaScript?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you explain the differences between SQL and NoSQL databases?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is Big O notation and how do you calculate it?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the Singleton pattern in software design", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How can I implement dependency injection in .NET?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the difference between synchronous and asynchronous execution", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the principles of functional programming?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How to create a thread in Java and manage its execution?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is memory management in the context of a programming language?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain how garbage collection works in Java", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the DOM and how is it manipulated?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Discuss the concept of encapsulation in object-oriented programming", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do I use regular expressions in Python for pattern matching?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the concept of state management in mobile app development", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the use of virtual environments in Python?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe how to optimize database queries", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the advantages of using TypeScript over JavaScript?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do event listeners work in web development?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain model-view-controller (MVC) in the context of web applications", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is a Graphical User Interface (GUI) and how is it implemented?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you explain the differences between classes and interfaces in Java?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How does the Model-View-ViewModel (MVVM) architectural pattern work?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are tuples in Python and how do they differ from lists?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the process of continuous integration in software development", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you manage state in a React Native application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are decorators in JavaScript and how are they used?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain how to use generators in Python to manage memory more efficiently", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the difference between procedural and object-oriented programming?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do I implement a hash table in C++?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is a blockchain and how does it work in the context of cryptocurrencies?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you describe the quicksort algorithm?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How are data structures like trees and graphs used in computing?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the purpose of a load balancer in a distributed system?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the differences between static and dynamic typing in programming languages", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How can I make a mobile app that works both on Android and iOS?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the best practices for securing a web application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe how unit testing works and why it is important", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the key features of the HTTP/2 protocol?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How does machine learning integrate with traditional software development?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you implement asynchronous methods in C#?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the Entity Framework in .NET and how do you use it?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you explain the concept of LINQ in .NET?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe how to manage memory in a .NET application", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are extension methods in C# and how are they declared?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the use of the async and await keywords in C#", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you handle exceptions in a .NET application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the purpose of the .NET Core and how does it differ from .NET Framework?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How can you improve the performance of a .NET application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are delegates in C# and how do you use them?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the process of creating a custom attribute in C#", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the differences between struct and class in C#", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is dependency injection in .NET and how is it implemented?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you serialize and deserialize JSON in .NET?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Discuss the role of interfaces in C# and how they enhance software design", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is MVC architecture in .NET and how do you implement it?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How to use SignalR for real-time web functionality in .NET?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the use of Reflection in C#", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the Garbage Collector in .NET and how does it work?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain event handling in C# with examples", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you use the Task Parallel Library in C# for multithreading?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the differences between .NET Core and .NET 5", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is Blazor in .NET and how can you build interactive web UIs with it?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the use of the NuGet package manager in .NET projects", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you implement global exception handling in a C# application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you explain how to use attributes in C# for metadata programming?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the benefits of using Entity Framework Core over ADO.NET?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How does the Dependency Injection container in .NET Core improve application design?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain how to secure a .NET application using OAuth and JWT", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is Razor syntax in ASP.NET Core and how does it facilitate dynamic HTML generation?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Discuss the role of middleware in ASP.NET Core applications", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How to manage session state in ASP.NET Core?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are Expression Trees in C# and what are their use cases?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the concept of code-first migration in Entity Framework Core", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you create and manage background services in .NET Core?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the IHostedService interface in .NET Core and how is it implemented?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Discuss the advantages of using the C# 9 record types", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How does the new nullable reference type feature in C# 8 improve code safety?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the performance benefits of using Span<T> and Memory<T> in C#?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe how to implement unit testing in a .NET Core application", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you manage state in Vue.js applications?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you explain the virtual DOM in React and how it works?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are props in React and how are they used?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the lifecycle methods of a React component", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you implement a global state management in Vue.js using Vuex?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are slots in Vue.js and how do they differ from React's props?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the use of keys in React lists", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How to handle forms in React?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is reactivity in Vue.js and how is it implemented?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you describe how to use computed properties in Vue.js?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How does the React Context API help in managing state?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are mixins in Vue.js and when should they be used?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the process of server-side rendering with Vue.js", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you use hooks in React to manage component lifecycle?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the benefits of using JSX in React?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain how to create dynamic routes in a React application", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you optimize performance in a Vue.js application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are higher-order components in React?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Discuss the differences between Vue.js and Angular", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you integrate TypeScript in a Vue.js project?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
     ("How do you set up Vue Router in a Vue.js project?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Can you explain how to manage state with Redux in a React application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the difference between a stateful and stateless component in React?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you perform form validation in Vue.js?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Discuss the use of the Virtual DOM in React and its benefits over direct DOM manipulation", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the concept of directives in Vue.js and provide examples", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How can you optimize React components to prevent unnecessary re-renders?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are functional components in React, and how do they differ from class components?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the transition component system in Vue.js and how to use it for animations", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you integrate third-party libraries, like D3.js, into a React application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What is the use of the provide and inject functions in Vue.js?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain how to use the Suspense component in React for data fetching", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are the key differences between Vue.js and React when it comes to handling user input?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you use React Router for managing navigation in a web application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Describe the pattern for managing global state in Vue.js without Vuex", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What are portals in React, and how can they be used?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("Explain the difference between computed properties and watchers in Vue.js", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How do you perform server-side rendering with a React application?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("What strategies can you use to handle SEO in Vue.js applications?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("How does React's new Hooks feature compare to Vue.js composition API?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("who are you", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("what are you", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),
    ("who created you", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 1.0, "READ":0.0, "DOCUMENTATION": 0.0}}),

    ("Read the file startup.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the file program.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the file csproj", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the file program.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("I want you to read the file program.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the file controller", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the controller", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the service", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read interface", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read controller", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read file", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the file and update the code", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the controller and update the code", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the controller and review the code", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the file and review the code", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Please read the file settings.xml", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Could you read the file config.json?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Kindly read the file Dockerfile", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Initiate a read of the file webpack.config.js", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Open and read the file README.md", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Please display the contents of the file appsettings.json", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Show me the file index.html", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Can you read out the script file?", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("I need you to read the file manifest.json", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Access and read the file global.asax", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read the file package.json and summarize it", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Please go through the file .gitignore", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Review the contents of the file .env", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Look into the file server.js and give feedback", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Analyze and read the file middleware.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Fetch and read the contents of the file .htaccess", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Display the text from the file constants.py", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Extract information from the file helpers.rb", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Check the details in the file main.go", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Inspect the file variables.scss for any errors", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Audit the file gulpfile.js and report any issues", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Access the file views.py and display its structure", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Navigate through the file routes.ts and explain its functions", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Read through the file userController.java and outline its methods", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Briefly go over the file style.css and check for redundancies", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Peruse the file data.xml and summarize the key points", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Explore the file logger.ts and identify potential improvements", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Survey the file component.jsx and provide a review", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Examine the file migrations.sql for any syntax errors", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),
    ("Review the configuration in the file settings.gradle", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":1.0, "DOCUMENTATION": 0.0}}),

    ("Document my code", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("document my code in dotnet/program.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("document my code in program.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("document the code in mycontroller.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("document the code in service.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Generate docs for service.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Document my file", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Document the functions in this module", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Create documentation the code in service.cs", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Create documentation for the new API endpoints", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Generate docs for the classes defined in this project", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Update the existing documentation with the latest changes", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Write detailed comments for each function in this script", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Create a help file for this utility", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Compile a user guide for the software", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Author a technical manual for our application", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Produce a README file for the repository", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Develop a how-to guide for the module installation", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Document usage examples for each method in the library", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Explain how to set up and run the project in the documentation", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Outline the project architecture in a document", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Document all dependencies used in the project", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Provide detailed API documentation for third-party developers", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Document the error handling procedures in the codebase", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Write up the data flow diagrams for system documentation", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Create a wiki page for the project's core functionalities", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Assemble a FAQ document for the software interface", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Outline the installation steps in the project documentation", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Draft the user manual for the application's latest version", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Prepare a troubleshooting guide for common issues in the system", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Document the steps to configure the software on different platforms", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Write documentation for the new features implemented this quarter", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Create detailed developer notes for the module updates", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Compile end-user documentation for the new system rollout", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Develop inline comments for critical sections of the source code", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Generate a code review guide for new developers", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Update the technical specification document with the latest changes", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}}),
    ("Write a comprehensive guide on how to use the internal API", {"cats": {"COMMAND": 0.0, "NOTACOMMAND": 0.0, "READ":0.0, "DOCUMENTATION": 1.0}})

]